name: "Release"
on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    strategy:
      fail-fast: false

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install pnpm
        run: npm install -g pnpm
      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "src-tauri -> target"
      - name: install app dependencies
        run: pnpm i
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__
          releaseName: "aptt v__VERSION__"
          releaseBody: |
            New features:
            - Submission history
            
            Bug fixes:
            - Textarea auto-focus works again
            - Submission errors were not caught 😱
          releaseDraft: false
          prerelease: false
