name: Test
on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: pnpm i

      - name: Run static tests
        run: pnpm test:static

      - name: Run unit tests
        run: pnpm test:unit
